#! /usr/bin/env python
#
# Support module generated by PAGE version 4.3
# In conjunction with Tcl version 8.6
#    Jul 11, 2014 11:24:49 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global tch42
    tch42 = IntVar()

    global tch43
    tch43 = IntVar()

    global nameInput
    nameInput = StringVar()

    global passwordInput
    passwordInput = StringVar()

    global userInput
    userInput = StringVar()

    global tch41
    tch41 = IntVar()

    global USER
    global FULLNAME
    global PASSWORD
    global doSharepoint
    global doElite
    global doCheck
def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


